PRESENTATION_TEX :=	pdflatex -interaction=batchmode
PRESENTATION_FILES :=	$(wildcard presentation/*.tex)
PRESENTATION_MAIN := presentation/presentation.pdf

presentation: $(PRESENTATION_MAIN)

$(PRESENTATION_MAIN) : %.pdf : %.tex $(PRESENTATION_FILES)
	cd $(<D); \
		$(PRESENTATION_TEX) $(<F); 

clean-presentation:
	-rm -f presentation/*.{aux,log,err,bbl,toc,blg,nav,out,snm}
	-rm -f $(PRESENTATION_MAIN)
	-rm -f presentation/*-eps-converted-to.pdf

clean: clean-presentation

.PHONY: clean-presentation presentation
