PAAL_SF_TESTS_DIR := paal_sf_tests
STEINER_TESTS_DIR = tests/steiner
ARCHIVE_FILE=steiner_forest_tests.tar.gz
TARGET_DIR=$(STEINER_TESTS_DIR)/$(PAAL_SF_TESTS_DIR)

$(TARGET_DIR):
	mkdir -p $(TARGET_DIR)
	tar xf $(STEINER_TESTS_DIR)/$(ARCHIVE_FILE) -C $(TARGET_DIR)

clean-sf_tests:
	rm -rf $(TARGET_DIR)

world: $(TARGET_DIR)

distclean: clean-sf_tests

.PHONY: clean-sf_tests
