#include <gtest/gtest.h>
#include <utility>
#include <string>
#include <fstream>  // NOLINT
#include <vector>
#include "steiner/SteinerForest.h"
#include "graph/AdjacencyMatrix.h"
#include "graph/AdjacencyLists.h"

#define TESTS_DIR "tests/steiner/"

class SteinerParam
{
  public:
    SteinerParam(std::string input, std::string output) : inputFilepath(input),
      outputFilepath(output)
    {
    }
    std::string inputFilepath;
    std::string outputFilepath;
};

class SteinerTest : public ::testing::TestWithParam<SteinerParam>
{
};

TEST_P(SteinerTest, Test)
{
  SteinerParam param = GetParam();
  std::ifstream inputData(param.inputFilepath);

  ASSERT_TRUE(inputData.is_open());

  size_t verticesCount, edgeCount;
  inputData >> verticesCount >> edgeCount;

  int sets[verticesCount];
  for (size_t i = 0; i < verticesCount; ++i)
  {
    inputData >> sets[i];
  }

  typedef AdjacencyLists<graph::undirected, double> graph_t;
  graph_t graph(verticesCount);
  for (size_t i = 0; i < edgeCount; ++i)
  {
    size_t a, b;
    double w;
    inputData >> a >> b >> w;
    graph.add_edge(a, b, w);
  }

  inputData.close();

  std::ifstream solutionData(param.outputFilepath);
  ASSERT_TRUE(solutionData.is_open());

  double bestKnownSolution;
  solutionData >> bestKnownSolution;
  solutionData.close();

  std::vector<graph_t::weighted_edge_t>
  steiner_forest_edges;

  SteinerForest<>(graph, sets, std::back_inserter(steiner_forest_edges));

  double solutionCost = 0.0;
  for (size_t i = 0; i < steiner_forest_edges.size(); ++i)
  {
    solutionCost += steiner_forest_edges[i].weight;
  }

  ASSERT_LE(solutionCost, 2 * bestKnownSolution);
  ASSERT_GE(solutionCost, bestKnownSolution);
}

INSTANTIATE_TEST_CASE_P(SteinerTree, SteinerTest,
    ::testing::Values(
      SteinerParam(std::string(TESTS_DIR "forest_tests/vazirani0.in"),
          std::string(TESTS_DIR "forest_tests/vazirani0.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/vazirani1.in"),
          std::string(TESTS_DIR "forest_tests/vazirani1.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/handcrafted0.in"),
          std::string(TESTS_DIR "forest_tests/handcrafted0.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/handcrafted1.in"),
          std::string(TESTS_DIR "forest_tests/handcrafted1.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/b01.in"),
          std::string(TESTS_DIR "tree_tests/b01.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/b02.in"),
          std::string(TESTS_DIR "tree_tests/b02.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/b03.in"),
          std::string(TESTS_DIR "tree_tests/b03.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/b04.in"),
          std::string(TESTS_DIR "tree_tests/b04.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/b05.in"),
          std::string(TESTS_DIR "tree_tests/b05.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/b06.in"),
          std::string(TESTS_DIR "tree_tests/b06.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/b07.in"),
          std::string(TESTS_DIR "tree_tests/b07.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/b08.in"),
          std::string(TESTS_DIR "tree_tests/b08.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/b09.in"),
          std::string(TESTS_DIR "tree_tests/b09.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/b10.in"),
          std::string(TESTS_DIR "tree_tests/b10.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/b11.in"),
          std::string(TESTS_DIR "tree_tests/b11.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/b12.in"),
          std::string(TESTS_DIR "tree_tests/b12.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/b13.in"),
          std::string(TESTS_DIR "tree_tests/b13.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/b14.in"),
          std::string(TESTS_DIR "tree_tests/b14.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/b15.in"),
          std::string(TESTS_DIR "tree_tests/b15.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/b16.in"),
          std::string(TESTS_DIR "tree_tests/b16.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/b17.in"),
          std::string(TESTS_DIR "tree_tests/b17.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/b18.in"),
          std::string(TESTS_DIR "tree_tests/b18.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/c01.in"),
          std::string(TESTS_DIR "tree_tests/c01.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/c02.in"),
          std::string(TESTS_DIR "tree_tests/c02.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/c03.in"),
          std::string(TESTS_DIR "tree_tests/c03.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/c04.in"),
          std::string(TESTS_DIR "tree_tests/c04.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/c05.in"),
          std::string(TESTS_DIR "tree_tests/c05.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/c06.in"),
          std::string(TESTS_DIR "tree_tests/c06.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/c07.in"),
          std::string(TESTS_DIR "tree_tests/c07.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/c08.in"),
          std::string(TESTS_DIR "tree_tests/c08.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/c09.in"),
          std::string(TESTS_DIR "tree_tests/c09.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/c10.in"),
          std::string(TESTS_DIR "tree_tests/c10.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/c11.in"),
          std::string(TESTS_DIR "tree_tests/c11.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/c12.in"),
          std::string(TESTS_DIR "tree_tests/c12.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/c13.in"),
          std::string(TESTS_DIR "tree_tests/c13.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/c14.in"),
          std::string(TESTS_DIR "tree_tests/c14.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/c15.in"),
          std::string(TESTS_DIR "tree_tests/c15.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/c16.in"),
          std::string(TESTS_DIR "tree_tests/c16.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/c17.in"),
          std::string(TESTS_DIR "tree_tests/c17.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/c18.in"),
          std::string(TESTS_DIR "tree_tests/c18.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/c19.in"),
          std::string(TESTS_DIR "tree_tests/c19.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/c20.in"),
          std::string(TESTS_DIR "tree_tests/c20.out"))));

INSTANTIATE_TEST_CASE_P(SteinerTree2, SteinerTest,
    ::testing::Values(
      SteinerParam(std::string(TESTS_DIR "tree_tests/d01.in"),
          std::string(TESTS_DIR "tree_tests/d01.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/d02.in"),
          std::string(TESTS_DIR "tree_tests/d02.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/d03.in"),
          std::string(TESTS_DIR "tree_tests/d03.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/d04.in"),
          std::string(TESTS_DIR "tree_tests/d04.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/d05.in"),
          std::string(TESTS_DIR "tree_tests/d05.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/d06.in"),
          std::string(TESTS_DIR "tree_tests/d06.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/d07.in"),
          std::string(TESTS_DIR "tree_tests/d07.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/d08.in"),
          std::string(TESTS_DIR "tree_tests/d08.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/d09.in"),
          std::string(TESTS_DIR "tree_tests/d09.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/d10.in"),
          std::string(TESTS_DIR "tree_tests/d10.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/d11.in"),
          std::string(TESTS_DIR "tree_tests/d11.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/d12.in"),
          std::string(TESTS_DIR "tree_tests/d12.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/d13.in"),
          std::string(TESTS_DIR "tree_tests/d13.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/d14.in"),
          std::string(TESTS_DIR "tree_tests/d14.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/d15.in"),
          std::string(TESTS_DIR "tree_tests/d15.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/d16.in"),
          std::string(TESTS_DIR "tree_tests/d16.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/d17.in"),
          std::string(TESTS_DIR "tree_tests/d17.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/d18.in"),
          std::string(TESTS_DIR "tree_tests/d18.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/d19.in"),
          std::string(TESTS_DIR "tree_tests/d19.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/d20.in"),
          std::string(TESTS_DIR "tree_tests/d20.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/e01.in"),
          std::string(TESTS_DIR "tree_tests/e01.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/e02.in"),
          std::string(TESTS_DIR "tree_tests/e02.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/e03.in"),
          std::string(TESTS_DIR "tree_tests/e03.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/e04.in"),
          std::string(TESTS_DIR "tree_tests/e04.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/e05.in"),
          std::string(TESTS_DIR "tree_tests/e05.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/e06.in"),
          std::string(TESTS_DIR "tree_tests/e06.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/e07.in"),
          std::string(TESTS_DIR "tree_tests/e07.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/e08.in"),
          std::string(TESTS_DIR "tree_tests/e08.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/e09.in"),
          std::string(TESTS_DIR "tree_tests/e09.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/e10.in"),
          std::string(TESTS_DIR "tree_tests/e10.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/e11.in"),
          std::string(TESTS_DIR "tree_tests/e11.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/e12.in"),
          std::string(TESTS_DIR "tree_tests/e12.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/e13.in"),
          std::string(TESTS_DIR "tree_tests/e13.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/e14.in"),
          std::string(TESTS_DIR "tree_tests/e14.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/e15.in"),
          std::string(TESTS_DIR "tree_tests/e15.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/e16.in"),
          std::string(TESTS_DIR "tree_tests/e16.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/e17.in"),
          std::string(TESTS_DIR "tree_tests/e17.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/e18.in"),
          std::string(TESTS_DIR "tree_tests/e18.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/e19.in"),
          std::string(TESTS_DIR "tree_tests/e19.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/e20.in"),
          std::string(TESTS_DIR "tree_tests/e20.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/mc11.in"),
          std::string(TESTS_DIR "tree_tests/mc11.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/mc13.in"),
          std::string(TESTS_DIR "tree_tests/mc13.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/mc2.in"),
          std::string(TESTS_DIR "tree_tests/mc2.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/mc3.in"),
          std::string(TESTS_DIR "tree_tests/mc3.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/mc7.in"),
          std::string(TESTS_DIR "tree_tests/mc7.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/mc8.in"),
          std::string(TESTS_DIR "tree_tests/mc8.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/berlin52.in"),
          std::string(TESTS_DIR "tree_tests/berlin52.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/brasil58.in"),
          std::string(TESTS_DIR "tree_tests/brasil58.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/world666.in"),
          std::string(TESTS_DIR "tree_tests/world666.out"))));

INSTANTIATE_TEST_CASE_P(SteinerTree3, SteinerTest,
    ::testing::Values(
      SteinerParam(std::string(TESTS_DIR "tree_tests/alue2087.in"),
          std::string(TESTS_DIR "tree_tests/alue2087.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/alue2105.in"),
          std::string(TESTS_DIR "tree_tests/alue2105.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/alue3146.in"),
          std::string(TESTS_DIR "tree_tests/alue3146.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/alue5067.in"),
          std::string(TESTS_DIR "tree_tests/alue5067.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/alue5345.in"),
          std::string(TESTS_DIR "tree_tests/alue5345.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/alue5623.in"),
          std::string(TESTS_DIR "tree_tests/alue5623.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/alue5901.in"),
          std::string(TESTS_DIR "tree_tests/alue5901.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/alue6179.in"),
          std::string(TESTS_DIR "tree_tests/alue6179.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/alue6457.in"),
          std::string(TESTS_DIR "tree_tests/alue6457.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/alue6735.in"),
          std::string(TESTS_DIR "tree_tests/alue6735.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/alue6951.in"),
          std::string(TESTS_DIR "tree_tests/alue6951.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/alue7065.in"),
          std::string(TESTS_DIR "tree_tests/alue7065.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/alue7066.in"),
          std::string(TESTS_DIR "tree_tests/alue7066.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/alue7080.in"),
          std::string(TESTS_DIR "tree_tests/alue7080.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/alue7229.in"),
          std::string(TESTS_DIR "tree_tests/alue7229.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/alut0787.in"),
          std::string(TESTS_DIR "tree_tests/alut0787.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/alut0805.in"),
          std::string(TESTS_DIR "tree_tests/alut0805.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/alut1181.in"),
          std::string(TESTS_DIR "tree_tests/alut1181.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/alut2010.in"),
          std::string(TESTS_DIR "tree_tests/alut2010.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/alut2288.in"),
          std::string(TESTS_DIR "tree_tests/alut2288.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/alut2566.in"),
          std::string(TESTS_DIR "tree_tests/alut2566.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/alut2610.in"),
          std::string(TESTS_DIR "tree_tests/alut2610.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/alut2625.in"),
          std::string(TESTS_DIR "tree_tests/alut2625.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/alut2764.in"),
          std::string(TESTS_DIR "tree_tests/alut2764.out"))));

INSTANTIATE_TEST_CASE_P(SteinerTree4, SteinerTest,
    ::testing::Values(
      SteinerParam(std::string(TESTS_DIR "tree_tests/diw0234.in"),
          std::string(TESTS_DIR "tree_tests/diw0234.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/diw0250.in"),
          std::string(TESTS_DIR "tree_tests/diw0250.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/diw0260.in"),
          std::string(TESTS_DIR "tree_tests/diw0260.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/diw0313.in"),
          std::string(TESTS_DIR "tree_tests/diw0313.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/diw0393.in"),
          std::string(TESTS_DIR "tree_tests/diw0393.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/diw0445.in"),
          std::string(TESTS_DIR "tree_tests/diw0445.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/diw0459.in"),
          std::string(TESTS_DIR "tree_tests/diw0459.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/diw0460.in"),
          std::string(TESTS_DIR "tree_tests/diw0460.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/diw0473.in"),
          std::string(TESTS_DIR "tree_tests/diw0473.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/diw0487.in"),
          std::string(TESTS_DIR "tree_tests/diw0487.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/diw0495.in"),
          std::string(TESTS_DIR "tree_tests/diw0495.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/diw0513.in"),
          std::string(TESTS_DIR "tree_tests/diw0513.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/diw0523.in"),
          std::string(TESTS_DIR "tree_tests/diw0523.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/diw0540.in"),
          std::string(TESTS_DIR "tree_tests/diw0540.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/diw0559.in"),
          std::string(TESTS_DIR "tree_tests/diw0559.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/diw0778.in"),
          std::string(TESTS_DIR "tree_tests/diw0778.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/diw0779.in"),
          std::string(TESTS_DIR "tree_tests/diw0779.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/diw0795.in"),
          std::string(TESTS_DIR "tree_tests/diw0795.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/diw0801.in"),
          std::string(TESTS_DIR "tree_tests/diw0801.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/diw0819.in"),
          std::string(TESTS_DIR "tree_tests/diw0819.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/diw0820.in"),
          std::string(TESTS_DIR "tree_tests/diw0820.out"))));

INSTANTIATE_TEST_CASE_P(SteinerTree5, SteinerTest,
    ::testing::Values(
      SteinerParam(std::string(TESTS_DIR "tree_tests/dmxa0296.in"),
          std::string(TESTS_DIR "tree_tests/dmxa0296.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/dmxa0368.in"),
          std::string(TESTS_DIR "tree_tests/dmxa0368.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/dmxa0454.in"),
          std::string(TESTS_DIR "tree_tests/dmxa0454.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/dmxa0628.in"),
          std::string(TESTS_DIR "tree_tests/dmxa0628.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/dmxa0734.in"),
          std::string(TESTS_DIR "tree_tests/dmxa0734.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/dmxa0848.in"),
          std::string(TESTS_DIR "tree_tests/dmxa0848.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/dmxa0903.in"),
          std::string(TESTS_DIR "tree_tests/dmxa0903.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/dmxa1010.in"),
          std::string(TESTS_DIR "tree_tests/dmxa1010.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/dmxa1109.in"),
          std::string(TESTS_DIR "tree_tests/dmxa1109.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/dmxa1200.in"),
          std::string(TESTS_DIR "tree_tests/dmxa1200.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/dmxa1304.in"),
          std::string(TESTS_DIR "tree_tests/dmxa1304.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/dmxa1516.in"),
          std::string(TESTS_DIR "tree_tests/dmxa1516.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/dmxa1721.in"),
          std::string(TESTS_DIR "tree_tests/dmxa1721.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/dmxa1801.in"),
          std::string(TESTS_DIR "tree_tests/dmxa1801.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/gap1307.in"),
          std::string(TESTS_DIR "tree_tests/gap1307.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/gap1413.in"),
          std::string(TESTS_DIR "tree_tests/gap1413.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/gap1500.in"),
          std::string(TESTS_DIR "tree_tests/gap1500.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/gap1810.in"),
          std::string(TESTS_DIR "tree_tests/gap1810.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/gap1904.in"),
          std::string(TESTS_DIR "tree_tests/gap1904.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/gap2007.in"),
          std::string(TESTS_DIR "tree_tests/gap2007.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/gap2119.in"),
          std::string(TESTS_DIR "tree_tests/gap2119.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/gap2740.in"),
          std::string(TESTS_DIR "tree_tests/gap2740.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/gap2800.in"),
          std::string(TESTS_DIR "tree_tests/gap2800.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/gap2975.in"),
          std::string(TESTS_DIR "tree_tests/gap2975.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/gap3036.in"),
          std::string(TESTS_DIR "tree_tests/gap3036.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/gap3100.in"),
          std::string(TESTS_DIR "tree_tests/gap3100.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/gap3128.in"),
          std::string(TESTS_DIR "tree_tests/gap3128.out"))));

INSTANTIATE_TEST_CASE_P(SteinerTree6, SteinerTest,
    ::testing::Values(
      SteinerParam(std::string(TESTS_DIR "tree_tests/msm0580.in"),
          std::string(TESTS_DIR "tree_tests/msm0580.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/msm0654.in"),
          std::string(TESTS_DIR "tree_tests/msm0654.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/msm0709.in"),
          std::string(TESTS_DIR "tree_tests/msm0709.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/msm0920.in"),
          std::string(TESTS_DIR "tree_tests/msm0920.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/msm1008.in"),
          std::string(TESTS_DIR "tree_tests/msm1008.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/msm1234.in"),
          std::string(TESTS_DIR "tree_tests/msm1234.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/msm1477.in"),
          std::string(TESTS_DIR "tree_tests/msm1477.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/msm1707.in"),
          std::string(TESTS_DIR "tree_tests/msm1707.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/msm1844.in"),
          std::string(TESTS_DIR "tree_tests/msm1844.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/msm1931.in"),
          std::string(TESTS_DIR "tree_tests/msm1931.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/msm2000.in"),
          std::string(TESTS_DIR "tree_tests/msm2000.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/msm2152.in"),
          std::string(TESTS_DIR "tree_tests/msm2152.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/msm2326.in"),
          std::string(TESTS_DIR "tree_tests/msm2326.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/msm2492.in"),
          std::string(TESTS_DIR "tree_tests/msm2492.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/msm2525.in"),
          std::string(TESTS_DIR "tree_tests/msm2525.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/msm2601.in"),
          std::string(TESTS_DIR "tree_tests/msm2601.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/msm2705.in"),
          std::string(TESTS_DIR "tree_tests/msm2705.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/msm2802.in"),
          std::string(TESTS_DIR "tree_tests/msm2802.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/msm2846.in"),
          std::string(TESTS_DIR "tree_tests/msm2846.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/msm3277.in"),
          std::string(TESTS_DIR "tree_tests/msm3277.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/msm3676.in"),
          std::string(TESTS_DIR "tree_tests/msm3676.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/msm3727.in"),
          std::string(TESTS_DIR "tree_tests/msm3727.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/msm3829.in"),
          std::string(TESTS_DIR "tree_tests/msm3829.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/msm4038.in"),
          std::string(TESTS_DIR "tree_tests/msm4038.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/msm4114.in"),
          std::string(TESTS_DIR "tree_tests/msm4114.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/msm4190.in"),
          std::string(TESTS_DIR "tree_tests/msm4190.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/msm4224.in"),
          std::string(TESTS_DIR "tree_tests/msm4224.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/msm4312.in"),
          std::string(TESTS_DIR "tree_tests/msm4312.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/msm4414.in"),
          std::string(TESTS_DIR "tree_tests/msm4414.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/msm4515.in"),
          std::string(TESTS_DIR "tree_tests/msm4515.out"))));

INSTANTIATE_TEST_CASE_P(SteinerTree7, SteinerTest,
    ::testing::Values(
      SteinerParam(std::string(TESTS_DIR "tree_tests/taq0014.in"),
          std::string(TESTS_DIR "tree_tests/taq0014.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/taq0023.in"),
          std::string(TESTS_DIR "tree_tests/taq0023.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/taq0365.in"),
          std::string(TESTS_DIR "tree_tests/taq0365.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/taq0377.in"),
          std::string(TESTS_DIR "tree_tests/taq0377.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/taq0431.in"),
          std::string(TESTS_DIR "tree_tests/taq0431.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/taq0631.in"),
          std::string(TESTS_DIR "tree_tests/taq0631.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/taq0739.in"),
          std::string(TESTS_DIR "tree_tests/taq0739.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/taq0741.in"),
          std::string(TESTS_DIR "tree_tests/taq0741.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/taq0751.in"),
          std::string(TESTS_DIR "tree_tests/taq0751.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/taq0891.in"),
          std::string(TESTS_DIR "tree_tests/taq0891.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/taq0903.in"),
          std::string(TESTS_DIR "tree_tests/taq0903.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/taq0910.in"),
          std::string(TESTS_DIR "tree_tests/taq0910.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/taq0920.in"),
          std::string(TESTS_DIR "tree_tests/taq0920.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/taq0978.in"),
          std::string(TESTS_DIR "tree_tests/taq0978.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es10fst01.in"),
          std::string(TESTS_DIR "tree_tests/es10fst01.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es10fst02.in"),
          std::string(TESTS_DIR "tree_tests/es10fst02.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es10fst03.in"),
          std::string(TESTS_DIR "tree_tests/es10fst03.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es10fst04.in"),
          std::string(TESTS_DIR "tree_tests/es10fst04.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es10fst05.in"),
          std::string(TESTS_DIR "tree_tests/es10fst05.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es10fst06.in"),
          std::string(TESTS_DIR "tree_tests/es10fst06.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es10fst07.in"),
          std::string(TESTS_DIR "tree_tests/es10fst07.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es10fst08.in"),
          std::string(TESTS_DIR "tree_tests/es10fst08.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es10fst09.in"),
          std::string(TESTS_DIR "tree_tests/es10fst09.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es10fst10.in"),
          std::string(TESTS_DIR "tree_tests/es10fst10.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es10fst11.in"),
          std::string(TESTS_DIR "tree_tests/es10fst11.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es10fst12.in"),
          std::string(TESTS_DIR "tree_tests/es10fst12.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es10fst13.in"),
          std::string(TESTS_DIR "tree_tests/es10fst13.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es10fst14.in"),
          std::string(TESTS_DIR "tree_tests/es10fst14.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es10fst15.in"),
          std::string(TESTS_DIR "tree_tests/es10fst15.out"))));

INSTANTIATE_TEST_CASE_P(SteinerTree8, SteinerTest,
    ::testing::Values(
      SteinerParam(std::string(TESTS_DIR "tree_tests/es20fst01.in"),
          std::string(TESTS_DIR "tree_tests/es20fst01.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es20fst02.in"),
          std::string(TESTS_DIR "tree_tests/es20fst02.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es20fst03.in"),
          std::string(TESTS_DIR "tree_tests/es20fst03.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es20fst04.in"),
          std::string(TESTS_DIR "tree_tests/es20fst04.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es20fst05.in"),
          std::string(TESTS_DIR "tree_tests/es20fst05.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es20fst06.in"),
          std::string(TESTS_DIR "tree_tests/es20fst06.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es20fst07.in"),
          std::string(TESTS_DIR "tree_tests/es20fst07.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es20fst08.in"),
          std::string(TESTS_DIR "tree_tests/es20fst08.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es20fst09.in"),
          std::string(TESTS_DIR "tree_tests/es20fst09.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es20fst10.in"),
          std::string(TESTS_DIR "tree_tests/es20fst10.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es20fst11.in"),
          std::string(TESTS_DIR "tree_tests/es20fst11.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es20fst12.in"),
          std::string(TESTS_DIR "tree_tests/es20fst12.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es20fst13.in"),
          std::string(TESTS_DIR "tree_tests/es20fst13.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es20fst14.in"),
          std::string(TESTS_DIR "tree_tests/es20fst14.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es20fst15.in"),
          std::string(TESTS_DIR "tree_tests/es20fst15.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es30fst01.in"),
          std::string(TESTS_DIR "tree_tests/es30fst01.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es30fst02.in"),
          std::string(TESTS_DIR "tree_tests/es30fst02.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es30fst03.in"),
          std::string(TESTS_DIR "tree_tests/es30fst03.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es30fst04.in"),
          std::string(TESTS_DIR "tree_tests/es30fst04.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es30fst05.in"),
          std::string(TESTS_DIR "tree_tests/es30fst05.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es30fst06.in"),
          std::string(TESTS_DIR "tree_tests/es30fst06.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es30fst07.in"),
          std::string(TESTS_DIR "tree_tests/es30fst07.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es30fst08.in"),
          std::string(TESTS_DIR "tree_tests/es30fst08.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es30fst09.in"),
          std::string(TESTS_DIR "tree_tests/es30fst09.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es30fst10.in"),
          std::string(TESTS_DIR "tree_tests/es30fst10.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es30fst11.in"),
          std::string(TESTS_DIR "tree_tests/es30fst11.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es30fst12.in"),
          std::string(TESTS_DIR "tree_tests/es30fst12.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es30fst13.in"),
          std::string(TESTS_DIR "tree_tests/es30fst13.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es30fst14.in"),
          std::string(TESTS_DIR "tree_tests/es30fst14.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es30fst15.in"),
          std::string(TESTS_DIR "tree_tests/es30fst15.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es40fst01.in"),
          std::string(TESTS_DIR "tree_tests/es40fst01.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es40fst02.in"),
          std::string(TESTS_DIR "tree_tests/es40fst02.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es40fst03.in"),
          std::string(TESTS_DIR "tree_tests/es40fst03.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es40fst04.in"),
          std::string(TESTS_DIR "tree_tests/es40fst04.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es40fst05.in"),
          std::string(TESTS_DIR "tree_tests/es40fst05.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es40fst06.in"),
          std::string(TESTS_DIR "tree_tests/es40fst06.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es40fst07.in"),
          std::string(TESTS_DIR "tree_tests/es40fst07.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es40fst08.in"),
          std::string(TESTS_DIR "tree_tests/es40fst08.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es40fst09.in"),
          std::string(TESTS_DIR "tree_tests/es40fst09.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es40fst10.in"),
          std::string(TESTS_DIR "tree_tests/es40fst10.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es40fst11.in"),
          std::string(TESTS_DIR "tree_tests/es40fst11.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es40fst12.in"),
          std::string(TESTS_DIR "tree_tests/es40fst12.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es40fst13.in"),
          std::string(TESTS_DIR "tree_tests/es40fst13.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es40fst14.in"),
          std::string(TESTS_DIR "tree_tests/es40fst14.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es40fst15.in"),
          std::string(TESTS_DIR "tree_tests/es40fst15.out"))));

INSTANTIATE_TEST_CASE_P(SteinerTree9, SteinerTest,
    ::testing::Values(
      SteinerParam(std::string(TESTS_DIR "tree_tests/es50fst01.in"),
          std::string(TESTS_DIR "tree_tests/es50fst01.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es50fst02.in"),
          std::string(TESTS_DIR "tree_tests/es50fst02.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es50fst03.in"),
          std::string(TESTS_DIR "tree_tests/es50fst03.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es50fst04.in"),
          std::string(TESTS_DIR "tree_tests/es50fst04.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es50fst05.in"),
          std::string(TESTS_DIR "tree_tests/es50fst05.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es50fst06.in"),
          std::string(TESTS_DIR "tree_tests/es50fst06.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es50fst07.in"),
          std::string(TESTS_DIR "tree_tests/es50fst07.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es50fst08.in"),
          std::string(TESTS_DIR "tree_tests/es50fst08.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es50fst09.in"),
          std::string(TESTS_DIR "tree_tests/es50fst09.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es50fst10.in"),
          std::string(TESTS_DIR "tree_tests/es50fst10.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es50fst11.in"),
          std::string(TESTS_DIR "tree_tests/es50fst11.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es50fst12.in"),
          std::string(TESTS_DIR "tree_tests/es50fst12.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es50fst13.in"),
          std::string(TESTS_DIR "tree_tests/es50fst13.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es50fst14.in"),
          std::string(TESTS_DIR "tree_tests/es50fst14.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es50fst15.in"),
          std::string(TESTS_DIR "tree_tests/es50fst15.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es60fst01.in"),
          std::string(TESTS_DIR "tree_tests/es60fst01.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es60fst02.in"),
          std::string(TESTS_DIR "tree_tests/es60fst02.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es60fst03.in"),
          std::string(TESTS_DIR "tree_tests/es60fst03.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es60fst04.in"),
          std::string(TESTS_DIR "tree_tests/es60fst04.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es60fst05.in"),
          std::string(TESTS_DIR "tree_tests/es60fst05.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es60fst06.in"),
          std::string(TESTS_DIR "tree_tests/es60fst06.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es60fst07.in"),
          std::string(TESTS_DIR "tree_tests/es60fst07.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es60fst08.in"),
          std::string(TESTS_DIR "tree_tests/es60fst08.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es60fst09.in"),
          std::string(TESTS_DIR "tree_tests/es60fst09.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es60fst10.in"),
          std::string(TESTS_DIR "tree_tests/es60fst10.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es60fst11.in"),
          std::string(TESTS_DIR "tree_tests/es60fst11.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es60fst12.in"),
          std::string(TESTS_DIR "tree_tests/es60fst12.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es60fst13.in"),
          std::string(TESTS_DIR "tree_tests/es60fst13.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es60fst14.in"),
          std::string(TESTS_DIR "tree_tests/es60fst14.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es60fst15.in"),
          std::string(TESTS_DIR "tree_tests/es60fst15.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es70fst01.in"),
          std::string(TESTS_DIR "tree_tests/es70fst01.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es70fst02.in"),
          std::string(TESTS_DIR "tree_tests/es70fst02.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es70fst03.in"),
          std::string(TESTS_DIR "tree_tests/es70fst03.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es70fst04.in"),
          std::string(TESTS_DIR "tree_tests/es70fst04.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es70fst05.in"),
          std::string(TESTS_DIR "tree_tests/es70fst05.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es70fst06.in"),
          std::string(TESTS_DIR "tree_tests/es70fst06.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es70fst07.in"),
          std::string(TESTS_DIR "tree_tests/es70fst07.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es70fst08.in"),
          std::string(TESTS_DIR "tree_tests/es70fst08.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es70fst09.in"),
          std::string(TESTS_DIR "tree_tests/es70fst09.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es70fst10.in"),
          std::string(TESTS_DIR "tree_tests/es70fst10.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es70fst11.in"),
          std::string(TESTS_DIR "tree_tests/es70fst11.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es70fst12.in"),
          std::string(TESTS_DIR "tree_tests/es70fst12.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es70fst13.in"),
          std::string(TESTS_DIR "tree_tests/es70fst13.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es70fst14.in"),
          std::string(TESTS_DIR "tree_tests/es70fst14.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es70fst15.in"),
          std::string(TESTS_DIR "tree_tests/es70fst15.out"))));

INSTANTIATE_TEST_CASE_P(SteinerTree10, SteinerTest,
    ::testing::Values(
      SteinerParam(std::string(TESTS_DIR "tree_tests/es80fst01.in"),
          std::string(TESTS_DIR "tree_tests/es80fst01.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es80fst02.in"),
          std::string(TESTS_DIR "tree_tests/es80fst02.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es80fst03.in"),
          std::string(TESTS_DIR "tree_tests/es80fst03.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es80fst04.in"),
          std::string(TESTS_DIR "tree_tests/es80fst04.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es80fst05.in"),
          std::string(TESTS_DIR "tree_tests/es80fst05.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es80fst06.in"),
          std::string(TESTS_DIR "tree_tests/es80fst06.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es80fst07.in"),
          std::string(TESTS_DIR "tree_tests/es80fst07.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es80fst08.in"),
          std::string(TESTS_DIR "tree_tests/es80fst08.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es80fst09.in"),
          std::string(TESTS_DIR "tree_tests/es80fst09.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es80fst10.in"),
          std::string(TESTS_DIR "tree_tests/es80fst10.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es80fst11.in"),
          std::string(TESTS_DIR "tree_tests/es80fst11.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es80fst12.in"),
          std::string(TESTS_DIR "tree_tests/es80fst12.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es80fst13.in"),
          std::string(TESTS_DIR "tree_tests/es80fst13.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es80fst14.in"),
          std::string(TESTS_DIR "tree_tests/es80fst14.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es80fst15.in"),
          std::string(TESTS_DIR "tree_tests/es80fst15.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es90fst01.in"),
          std::string(TESTS_DIR "tree_tests/es90fst01.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es90fst02.in"),
          std::string(TESTS_DIR "tree_tests/es90fst02.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es90fst03.in"),
          std::string(TESTS_DIR "tree_tests/es90fst03.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es90fst04.in"),
          std::string(TESTS_DIR "tree_tests/es90fst04.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es90fst05.in"),
          std::string(TESTS_DIR "tree_tests/es90fst05.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es90fst06.in"),
          std::string(TESTS_DIR "tree_tests/es90fst06.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es90fst07.in"),
          std::string(TESTS_DIR "tree_tests/es90fst07.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es90fst08.in"),
          std::string(TESTS_DIR "tree_tests/es90fst08.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es90fst09.in"),
          std::string(TESTS_DIR "tree_tests/es90fst09.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es90fst10.in"),
          std::string(TESTS_DIR "tree_tests/es90fst10.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es90fst11.in"),
          std::string(TESTS_DIR "tree_tests/es90fst11.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es90fst12.in"),
          std::string(TESTS_DIR "tree_tests/es90fst12.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es90fst13.in"),
          std::string(TESTS_DIR "tree_tests/es90fst13.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es90fst14.in"),
          std::string(TESTS_DIR "tree_tests/es90fst14.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es90fst15.in"),
          std::string(TESTS_DIR "tree_tests/es90fst15.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es100fst01.in"),
          std::string(TESTS_DIR "tree_tests/es100fst01.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es100fst02.in"),
          std::string(TESTS_DIR "tree_tests/es100fst02.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es100fst03.in"),
          std::string(TESTS_DIR "tree_tests/es100fst03.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es100fst04.in"),
          std::string(TESTS_DIR "tree_tests/es100fst04.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es100fst05.in"),
          std::string(TESTS_DIR "tree_tests/es100fst05.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es100fst06.in"),
          std::string(TESTS_DIR "tree_tests/es100fst06.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es100fst07.in"),
          std::string(TESTS_DIR "tree_tests/es100fst07.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es100fst08.in"),
          std::string(TESTS_DIR "tree_tests/es100fst08.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es100fst09.in"),
          std::string(TESTS_DIR "tree_tests/es100fst09.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es100fst10.in"),
          std::string(TESTS_DIR "tree_tests/es100fst10.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es100fst11.in"),
          std::string(TESTS_DIR "tree_tests/es100fst11.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es100fst12.in"),
          std::string(TESTS_DIR "tree_tests/es100fst12.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es100fst13.in"),
          std::string(TESTS_DIR "tree_tests/es100fst13.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es100fst14.in"),
          std::string(TESTS_DIR "tree_tests/es100fst14.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es100fst15.in"),
          std::string(TESTS_DIR "tree_tests/es100fst15.out"))));

INSTANTIATE_TEST_CASE_P(SteinerTree11, SteinerTest,
    ::testing::Values(
      SteinerParam(std::string(TESTS_DIR "tree_tests/es250fst01.in"),
          std::string(TESTS_DIR "tree_tests/es250fst01.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es250fst02.in"),
          std::string(TESTS_DIR "tree_tests/es250fst02.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es250fst03.in"),
          std::string(TESTS_DIR "tree_tests/es250fst03.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es250fst04.in"),
          std::string(TESTS_DIR "tree_tests/es250fst04.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es250fst05.in"),
          std::string(TESTS_DIR "tree_tests/es250fst05.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es250fst06.in"),
          std::string(TESTS_DIR "tree_tests/es250fst06.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es250fst07.in"),
          std::string(TESTS_DIR "tree_tests/es250fst07.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es250fst08.in"),
          std::string(TESTS_DIR "tree_tests/es250fst08.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es250fst09.in"),
          std::string(TESTS_DIR "tree_tests/es250fst09.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es250fst10.in"),
          std::string(TESTS_DIR "tree_tests/es250fst10.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es250fst11.in"),
          std::string(TESTS_DIR "tree_tests/es250fst11.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es250fst12.in"),
          std::string(TESTS_DIR "tree_tests/es250fst12.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es250fst13.in"),
          std::string(TESTS_DIR "tree_tests/es250fst13.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es250fst14.in"),
          std::string(TESTS_DIR "tree_tests/es250fst14.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es250fst15.in"),
          std::string(TESTS_DIR "tree_tests/es250fst15.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es500fst01.in"),
          std::string(TESTS_DIR "tree_tests/es500fst01.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es500fst02.in"),
          std::string(TESTS_DIR "tree_tests/es500fst02.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es500fst03.in"),
          std::string(TESTS_DIR "tree_tests/es500fst03.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es500fst04.in"),
          std::string(TESTS_DIR "tree_tests/es500fst04.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es500fst05.in"),
          std::string(TESTS_DIR "tree_tests/es500fst05.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es500fst06.in"),
          std::string(TESTS_DIR "tree_tests/es500fst06.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es500fst07.in"),
          std::string(TESTS_DIR "tree_tests/es500fst07.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es500fst08.in"),
          std::string(TESTS_DIR "tree_tests/es500fst08.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es500fst09.in"),
          std::string(TESTS_DIR "tree_tests/es500fst09.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es500fst10.in"),
          std::string(TESTS_DIR "tree_tests/es500fst10.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es500fst11.in"),
          std::string(TESTS_DIR "tree_tests/es500fst11.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es500fst12.in"),
          std::string(TESTS_DIR "tree_tests/es500fst12.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es500fst13.in"),
          std::string(TESTS_DIR "tree_tests/es500fst13.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es500fst14.in"),
          std::string(TESTS_DIR "tree_tests/es500fst14.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es500fst15.in"),
          std::string(TESTS_DIR "tree_tests/es500fst15.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es1000fst01.in"),
          std::string(TESTS_DIR "tree_tests/es1000fst01.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es1000fst02.in"),
          std::string(TESTS_DIR "tree_tests/es1000fst02.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es1000fst03.in"),
          std::string(TESTS_DIR "tree_tests/es1000fst03.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es1000fst04.in"),
          std::string(TESTS_DIR "tree_tests/es1000fst04.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es1000fst05.in"),
          std::string(TESTS_DIR "tree_tests/es1000fst05.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es1000fst06.in"),
          std::string(TESTS_DIR "tree_tests/es1000fst06.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es1000fst07.in"),
          std::string(TESTS_DIR "tree_tests/es1000fst07.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es1000fst08.in"),
          std::string(TESTS_DIR "tree_tests/es1000fst08.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es1000fst09.in"),
          std::string(TESTS_DIR "tree_tests/es1000fst09.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es1000fst10.in"),
          std::string(TESTS_DIR "tree_tests/es1000fst10.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es1000fst11.in"),
          std::string(TESTS_DIR "tree_tests/es1000fst11.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es1000fst12.in"),
          std::string(TESTS_DIR "tree_tests/es1000fst12.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es1000fst13.in"),
          std::string(TESTS_DIR "tree_tests/es1000fst13.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es1000fst14.in"),
          std::string(TESTS_DIR "tree_tests/es1000fst14.out")),
      SteinerParam(std::string(TESTS_DIR "tree_tests/es1000fst15.in"),
          std::string(TESTS_DIR "tree_tests/es1000fst15.out"))));

INSTANTIATE_TEST_CASE_P(SteinerTree12, SteinerTest,
    ::testing::Values(
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_small_test1.in"),
          std::string(TESTS_DIR "forest_tests/lp_small_test1.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_small_test2.in"),
          std::string(TESTS_DIR "forest_tests/lp_small_test2.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_small_test3.in"),
          std::string(TESTS_DIR "forest_tests/lp_small_test3.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_small_test4.in"),
          std::string(TESTS_DIR "forest_tests/lp_small_test4.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_small_test5.in"),
          std::string(TESTS_DIR "forest_tests/lp_small_test5.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_small_test6.in"),
          std::string(TESTS_DIR "forest_tests/lp_small_test6.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_small_test7.in"),
          std::string(TESTS_DIR "forest_tests/lp_small_test7.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_small_test8.in"),
          std::string(TESTS_DIR "forest_tests/lp_small_test8.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_small_test9.in"),
          std::string(TESTS_DIR "forest_tests/lp_small_test9.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_small_test10.in"),
          std::string(TESTS_DIR "forest_tests/lp_small_test10.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_small_test11.in"),
          std::string(TESTS_DIR "forest_tests/lp_small_test11.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_small_test12.in"),
          std::string(TESTS_DIR "forest_tests/lp_small_test12.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_small_test13.in"),
          std::string(TESTS_DIR "forest_tests/lp_small_test13.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_small_test14.in"),
          std::string(TESTS_DIR "forest_tests/lp_small_test14.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_small_test15.in"),
          std::string(TESTS_DIR "forest_tests/lp_small_test15.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_small_test16.in"),
          std::string(TESTS_DIR "forest_tests/lp_small_test16.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_small_test17.in"),
          std::string(TESTS_DIR "forest_tests/lp_small_test17.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_small_test18.in"),
          std::string(TESTS_DIR "forest_tests/lp_small_test18.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_small_test19.in"),
          std::string(TESTS_DIR "forest_tests/lp_small_test19.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_small_test20.in"),
          std::string(TESTS_DIR "forest_tests/lp_small_test20.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_small_test21.in"),
          std::string(TESTS_DIR "forest_tests/lp_small_test21.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_small_test22.in"),
          std::string(TESTS_DIR "forest_tests/lp_small_test22.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_small_test23.in"),
          std::string(TESTS_DIR "forest_tests/lp_small_test23.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_small_test24.in"),
          std::string(TESTS_DIR "forest_tests/lp_small_test24.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_small_test25.in"),
          std::string(TESTS_DIR "forest_tests/lp_small_test25.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_small_test26.in"),
          std::string(TESTS_DIR "forest_tests/lp_small_test26.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_small_test27.in"),
          std::string(TESTS_DIR "forest_tests/lp_small_test27.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_small_test28.in"),
          std::string(TESTS_DIR "forest_tests/lp_small_test28.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_small_test29.in"),
          std::string(TESTS_DIR "forest_tests/lp_small_test29.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_small_test30.in"),
          std::string(TESTS_DIR "forest_tests/lp_small_test30.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_small_test31.in"),
          std::string(TESTS_DIR "forest_tests/lp_small_test31.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_small_test32.in"),
          std::string(TESTS_DIR "forest_tests/lp_small_test32.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_small_test33.in"),
          std::string(TESTS_DIR "forest_tests/lp_small_test33.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_small_test34.in"),
          std::string(TESTS_DIR "forest_tests/lp_small_test34.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_small_test35.in"),
          std::string(TESTS_DIR "forest_tests/lp_small_test35.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_small_test36.in"),
          std::string(TESTS_DIR "forest_tests/lp_small_test36.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_small_test37.in"),
          std::string(TESTS_DIR "forest_tests/lp_small_test37.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_small_test38.in"),
          std::string(TESTS_DIR "forest_tests/lp_small_test38.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_small_test39.in"),
          std::string(TESTS_DIR "forest_tests/lp_small_test39.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_small_test40.in"),
          std::string(TESTS_DIR "forest_tests/lp_small_test40.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_small_test41.in"),
          std::string(TESTS_DIR "forest_tests/lp_small_test41.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_small_test42.in"),
          std::string(TESTS_DIR "forest_tests/lp_small_test42.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_small_test43.in"),
          std::string(TESTS_DIR "forest_tests/lp_small_test43.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_small_test44.in"),
          std::string(TESTS_DIR "forest_tests/lp_small_test44.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_small_test45.in"),
          std::string(TESTS_DIR "forest_tests/lp_small_test45.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_small_test46.in"),
          std::string(TESTS_DIR "forest_tests/lp_small_test46.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_small_test47.in"),
          std::string(TESTS_DIR "forest_tests/lp_small_test47.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_small_test48.in"),
          std::string(TESTS_DIR "forest_tests/lp_small_test48.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_small_test49.in"),
          std::string(TESTS_DIR "forest_tests/lp_small_test49.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_small_test50.in"),
          std::string(TESTS_DIR "forest_tests/lp_small_test50.out"))));

INSTANTIATE_TEST_CASE_P(SteinerForest, SteinerTest,
    ::testing::Values(
      SteinerParam(
        std::string(TESTS_DIR "forest_tests/lp_very_small_test1.in"),
        std::string(TESTS_DIR "forest_tests/lp_very_small_test1.out")),
      SteinerParam(
        std::string(TESTS_DIR "forest_tests/lp_very_small_test2.in"),
        std::string(TESTS_DIR "forest_tests/lp_very_small_test2.out")),
      SteinerParam(
        std::string(TESTS_DIR "forest_tests/lp_very_small_test3.in"),
        std::string(TESTS_DIR "forest_tests/lp_very_small_test3.out")),
      SteinerParam(
        std::string(TESTS_DIR "forest_tests/lp_very_small_test4.in"),
        std::string(TESTS_DIR "forest_tests/lp_very_small_test4.out")),
      SteinerParam(
        std::string(TESTS_DIR "forest_tests/lp_very_small_test5.in"),
        std::string(TESTS_DIR "forest_tests/lp_very_small_test5.out")),
      SteinerParam(
        std::string(TESTS_DIR "forest_tests/lp_very_small_test6.in"),
        std::string(TESTS_DIR "forest_tests/lp_very_small_test6.out")),
      SteinerParam(
        std::string(TESTS_DIR "forest_tests/lp_very_small_test7.in"),
        std::string(TESTS_DIR "forest_tests/lp_very_small_test7.out")),
      SteinerParam(
        std::string(TESTS_DIR "forest_tests/lp_very_small_test8.in"),
        std::string(TESTS_DIR "forest_tests/lp_very_small_test8.out")),
      SteinerParam(
        std::string(TESTS_DIR "forest_tests/lp_very_small_test9.in"),
        std::string(TESTS_DIR "forest_tests/lp_very_small_test9.out")),
      SteinerParam(
        std::string(TESTS_DIR "forest_tests/lp_very_small_test10.in"),
        std::string(TESTS_DIR "forest_tests/lp_very_small_test10.out")),
      SteinerParam(
        std::string(TESTS_DIR "forest_tests/lp_very_small_test11.in"),
        std::string(TESTS_DIR "forest_tests/lp_very_small_test11.out")),
      SteinerParam(
        std::string(TESTS_DIR "forest_tests/lp_very_small_test12.in"),
        std::string(TESTS_DIR "forest_tests/lp_very_small_test12.out")),
      SteinerParam(
        std::string(TESTS_DIR "forest_tests/lp_very_small_test13.in"),
        std::string(TESTS_DIR "forest_tests/lp_very_small_test13.out")),
      SteinerParam(
        std::string(TESTS_DIR "forest_tests/lp_very_small_test14.in"),
        std::string(TESTS_DIR "forest_tests/lp_very_small_test14.out")),
      SteinerParam(
        std::string(TESTS_DIR "forest_tests/lp_very_small_test15.in"),
        std::string(TESTS_DIR "forest_tests/lp_very_small_test15.out")),
      SteinerParam(
        std::string(TESTS_DIR "forest_tests/lp_very_small_test16.in"),
        std::string(TESTS_DIR "forest_tests/lp_very_small_test16.out")),
      SteinerParam(
        std::string(TESTS_DIR "forest_tests/lp_very_small_test17.in"),
        std::string(TESTS_DIR "forest_tests/lp_very_small_test17.out")),
      SteinerParam(
        std::string(TESTS_DIR "forest_tests/lp_very_small_test18.in"),
        std::string(TESTS_DIR "forest_tests/lp_very_small_test18.out")),
      SteinerParam(
        std::string(TESTS_DIR "forest_tests/lp_very_small_test19.in"),
        std::string(TESTS_DIR "forest_tests/lp_very_small_test19.out")),
      SteinerParam(
        std::string(TESTS_DIR "forest_tests/lp_very_small_test20.in"),
        std::string(TESTS_DIR "forest_tests/lp_very_small_test20.out")),
      SteinerParam(
        std::string(TESTS_DIR "forest_tests/lp_very_small_test21.in"),
        std::string(TESTS_DIR "forest_tests/lp_very_small_test21.out")),
      SteinerParam(
        std::string(TESTS_DIR "forest_tests/lp_very_small_test22.in"),
        std::string(TESTS_DIR "forest_tests/lp_very_small_test22.out")),
      SteinerParam(
        std::string(TESTS_DIR "forest_tests/lp_very_small_test23.in"),
        std::string(TESTS_DIR "forest_tests/lp_very_small_test23.out")),
      SteinerParam(
        std::string(TESTS_DIR "forest_tests/lp_very_small_test24.in"),
        std::string(TESTS_DIR "forest_tests/lp_very_small_test24.out")),
      SteinerParam(
        std::string(TESTS_DIR "forest_tests/lp_very_small_test25.in"),
        std::string(TESTS_DIR "forest_tests/lp_very_small_test25.out")),
      SteinerParam(
        std::string(TESTS_DIR "forest_tests/lp_very_small_test26.in"),
        std::string(TESTS_DIR "forest_tests/lp_very_small_test26.out")),
      SteinerParam(
        std::string(TESTS_DIR "forest_tests/lp_very_small_test27.in"),
        std::string(TESTS_DIR "forest_tests/lp_very_small_test27.out")),
      SteinerParam(
        std::string(TESTS_DIR "forest_tests/lp_very_small_test28.in"),
        std::string(TESTS_DIR "forest_tests/lp_very_small_test28.out")),
      SteinerParam(
        std::string(TESTS_DIR "forest_tests/lp_very_small_test29.in"),
        std::string(TESTS_DIR "forest_tests/lp_very_small_test29.out")),
      SteinerParam(
        std::string(TESTS_DIR "forest_tests/lp_very_small_test30.in"),
        std::string(TESTS_DIR "forest_tests/lp_very_small_test30.out")),
      SteinerParam(
        std::string(TESTS_DIR "forest_tests/lp_very_small_test31.in"),
        std::string(TESTS_DIR "forest_tests/lp_very_small_test31.out")),
      SteinerParam(
        std::string(TESTS_DIR "forest_tests/lp_very_small_test32.in"),
        std::string(TESTS_DIR "forest_tests/lp_very_small_test32.out")),
      SteinerParam(
        std::string(TESTS_DIR "forest_tests/lp_very_small_test33.in"),
        std::string(TESTS_DIR "forest_tests/lp_very_small_test33.out")),
      SteinerParam(
        std::string(TESTS_DIR "forest_tests/lp_very_small_test34.in"),
        std::string(TESTS_DIR "forest_tests/lp_very_small_test34.out")),
      SteinerParam(
        std::string(TESTS_DIR "forest_tests/lp_very_small_test35.in"),
        std::string(TESTS_DIR "forest_tests/lp_very_small_test35.out")),
      SteinerParam(
        std::string(TESTS_DIR "forest_tests/lp_very_small_test36.in"),
        std::string(TESTS_DIR "forest_tests/lp_very_small_test36.out")),
      SteinerParam(
        std::string(TESTS_DIR "forest_tests/lp_very_small_test37.in"),
        std::string(TESTS_DIR "forest_tests/lp_very_small_test37.out")),
      SteinerParam(
        std::string(TESTS_DIR "forest_tests/lp_very_small_test38.in"),
        std::string(TESTS_DIR "forest_tests/lp_very_small_test38.out")),
      SteinerParam(
        std::string(TESTS_DIR "forest_tests/lp_very_small_test39.in"),
        std::string(TESTS_DIR "forest_tests/lp_very_small_test39.out")),
      SteinerParam(
        std::string(TESTS_DIR "forest_tests/lp_very_small_test40.in"),
        std::string(TESTS_DIR "forest_tests/lp_very_small_test40.out")),
      SteinerParam(
        std::string(TESTS_DIR "forest_tests/lp_very_small_test41.in"),
        std::string(TESTS_DIR "forest_tests/lp_very_small_test41.out")),
      SteinerParam(
        std::string(TESTS_DIR "forest_tests/lp_very_small_test42.in"),
        std::string(TESTS_DIR "forest_tests/lp_very_small_test42.out")),
      SteinerParam(
        std::string(TESTS_DIR "forest_tests/lp_very_small_test43.in"),
        std::string(TESTS_DIR "forest_tests/lp_very_small_test43.out")),
      SteinerParam(
        std::string(TESTS_DIR "forest_tests/lp_very_small_test44.in"),
        std::string(TESTS_DIR "forest_tests/lp_very_small_test44.out")),
      SteinerParam(
        std::string(TESTS_DIR "forest_tests/lp_very_small_test45.in"),
        std::string(TESTS_DIR "forest_tests/lp_very_small_test45.out")),
      SteinerParam(
        std::string(TESTS_DIR "forest_tests/lp_very_small_test46.in"),
        std::string(TESTS_DIR "forest_tests/lp_very_small_test46.out")),
      SteinerParam(
        std::string(TESTS_DIR "forest_tests/lp_very_small_test47.in"),
        std::string(TESTS_DIR "forest_tests/lp_very_small_test47.out")),
      SteinerParam(
        std::string(TESTS_DIR "forest_tests/lp_very_small_test48.in"),
        std::string(TESTS_DIR "forest_tests/lp_very_small_test48.out")),
      SteinerParam(
        std::string(TESTS_DIR "forest_tests/lp_very_small_test49.in"),
        std::string(TESTS_DIR "forest_tests/lp_very_small_test49.out")),
      SteinerParam(
        std::string(TESTS_DIR "forest_tests/lp_very_small_test50.in"),
        std::string(TESTS_DIR "forest_tests/lp_very_small_test50.out"))));

INSTANTIATE_TEST_CASE_P(SteinerForest2, SteinerTest,
    ::testing::Values(
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_4groups_test1.in"),
          std::string(TESTS_DIR "forest_tests/lp_4groups_test1.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_4groups_test2.in"),
          std::string(TESTS_DIR "forest_tests/lp_4groups_test2.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_4groups_test3.in"),
          std::string(TESTS_DIR "forest_tests/lp_4groups_test3.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_4groups_test4.in"),
          std::string(TESTS_DIR "forest_tests/lp_4groups_test4.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_4groups_test5.in"),
          std::string(TESTS_DIR "forest_tests/lp_4groups_test5.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_4groups_test6.in"),
          std::string(TESTS_DIR "forest_tests/lp_4groups_test6.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_4groups_test7.in"),
          std::string(TESTS_DIR "forest_tests/lp_4groups_test7.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_4groups_test8.in"),
          std::string(TESTS_DIR "forest_tests/lp_4groups_test8.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_4groups_test9.in"),
          std::string(TESTS_DIR "forest_tests/lp_4groups_test9.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_4groups_test10.in"),
          std::string(TESTS_DIR "forest_tests/lp_4groups_test10.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_4groups_test11.in"),
          std::string(TESTS_DIR "forest_tests/lp_4groups_test11.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_4groups_test12.in"),
          std::string(TESTS_DIR "forest_tests/lp_4groups_test12.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_4groups_test13.in"),
          std::string(TESTS_DIR "forest_tests/lp_4groups_test13.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_4groups_test14.in"),
          std::string(TESTS_DIR "forest_tests/lp_4groups_test14.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_4groups_test15.in"),
          std::string(TESTS_DIR "forest_tests/lp_4groups_test15.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_4groups_test16.in"),
          std::string(TESTS_DIR "forest_tests/lp_4groups_test16.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_4groups_test17.in"),
          std::string(TESTS_DIR "forest_tests/lp_4groups_test17.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_4groups_test18.in"),
          std::string(TESTS_DIR "forest_tests/lp_4groups_test18.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_4groups_test19.in"),
          std::string(TESTS_DIR "forest_tests/lp_4groups_test19.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_4groups_test20.in"),
          std::string(TESTS_DIR "forest_tests/lp_4groups_test20.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_4groups_test21.in"),
          std::string(TESTS_DIR "forest_tests/lp_4groups_test21.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_4groups_test22.in"),
          std::string(TESTS_DIR "forest_tests/lp_4groups_test22.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_4groups_test23.in"),
          std::string(TESTS_DIR "forest_tests/lp_4groups_test23.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_4groups_test24.in"),
          std::string(TESTS_DIR "forest_tests/lp_4groups_test24.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_4groups_test25.in"),
          std::string(TESTS_DIR "forest_tests/lp_4groups_test25.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_4groups_test26.in"),
          std::string(TESTS_DIR "forest_tests/lp_4groups_test26.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_4groups_test27.in"),
          std::string(TESTS_DIR "forest_tests/lp_4groups_test27.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_4groups_test28.in"),
          std::string(TESTS_DIR "forest_tests/lp_4groups_test28.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_4groups_test29.in"),
          std::string(TESTS_DIR "forest_tests/lp_4groups_test29.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_4groups_test30.in"),
          std::string(TESTS_DIR "forest_tests/lp_4groups_test30.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_4groups_test31.in"),
          std::string(TESTS_DIR "forest_tests/lp_4groups_test31.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_4groups_test32.in"),
          std::string(TESTS_DIR "forest_tests/lp_4groups_test32.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_4groups_test33.in"),
          std::string(TESTS_DIR "forest_tests/lp_4groups_test33.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_4groups_test34.in"),
          std::string(TESTS_DIR "forest_tests/lp_4groups_test34.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_4groups_test35.in"),
          std::string(TESTS_DIR "forest_tests/lp_4groups_test35.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_4groups_test36.in"),
          std::string(TESTS_DIR "forest_tests/lp_4groups_test36.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_4groups_test37.in"),
          std::string(TESTS_DIR "forest_tests/lp_4groups_test37.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_4groups_test38.in"),
          std::string(TESTS_DIR "forest_tests/lp_4groups_test38.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_4groups_test39.in"),
          std::string(TESTS_DIR "forest_tests/lp_4groups_test39.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_4groups_test40.in"),
          std::string(TESTS_DIR "forest_tests/lp_4groups_test40.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_4groups_test41.in"),
          std::string(TESTS_DIR "forest_tests/lp_4groups_test41.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_4groups_test42.in"),
          std::string(TESTS_DIR "forest_tests/lp_4groups_test42.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_4groups_test43.in"),
          std::string(TESTS_DIR "forest_tests/lp_4groups_test43.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_4groups_test44.in"),
          std::string(TESTS_DIR "forest_tests/lp_4groups_test44.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_4groups_test45.in"),
          std::string(TESTS_DIR "forest_tests/lp_4groups_test45.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_4groups_test46.in"),
          std::string(TESTS_DIR "forest_tests/lp_4groups_test46.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_4groups_test47.in"),
          std::string(TESTS_DIR "forest_tests/lp_4groups_test47.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_4groups_test48.in"),
          std::string(TESTS_DIR "forest_tests/lp_4groups_test48.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_4groups_test49.in"),
          std::string(TESTS_DIR "forest_tests/lp_4groups_test49.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_4groups_test50.in"),
          std::string(TESTS_DIR "forest_tests/lp_4groups_test50.out"))));

INSTANTIATE_TEST_CASE_P(SteinerForest3, SteinerTest,
    ::testing::Values(
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_3groups_test1.in"),
          std::string(TESTS_DIR "forest_tests/lp_3groups_test1.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_3groups_test2.in"),
          std::string(TESTS_DIR "forest_tests/lp_3groups_test2.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_3groups_test3.in"),
          std::string(TESTS_DIR "forest_tests/lp_3groups_test3.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_3groups_test4.in"),
          std::string(TESTS_DIR "forest_tests/lp_3groups_test4.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_3groups_test5.in"),
          std::string(TESTS_DIR "forest_tests/lp_3groups_test5.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_3groups_test6.in"),
          std::string(TESTS_DIR "forest_tests/lp_3groups_test6.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_3groups_test7.in"),
          std::string(TESTS_DIR "forest_tests/lp_3groups_test7.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_3groups_test8.in"),
          std::string(TESTS_DIR "forest_tests/lp_3groups_test8.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_3groups_test9.in"),
          std::string(TESTS_DIR "forest_tests/lp_3groups_test9.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_3groups_test10.in"),
          std::string(TESTS_DIR "forest_tests/lp_3groups_test10.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_3groups_test11.in"),
          std::string(TESTS_DIR "forest_tests/lp_3groups_test11.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_3groups_test12.in"),
          std::string(TESTS_DIR "forest_tests/lp_3groups_test12.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_3groups_test13.in"),
          std::string(TESTS_DIR "forest_tests/lp_3groups_test13.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_3groups_test14.in"),
          std::string(TESTS_DIR "forest_tests/lp_3groups_test14.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_3groups_test15.in"),
          std::string(TESTS_DIR "forest_tests/lp_3groups_test15.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_3groups_test16.in"),
          std::string(TESTS_DIR "forest_tests/lp_3groups_test16.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_3groups_test17.in"),
          std::string(TESTS_DIR "forest_tests/lp_3groups_test17.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_3groups_test18.in"),
          std::string(TESTS_DIR "forest_tests/lp_3groups_test18.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_3groups_test19.in"),
          std::string(TESTS_DIR "forest_tests/lp_3groups_test19.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_3groups_test20.in"),
          std::string(TESTS_DIR "forest_tests/lp_3groups_test20.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_3groups_test21.in"),
          std::string(TESTS_DIR "forest_tests/lp_3groups_test21.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_3groups_test22.in"),
          std::string(TESTS_DIR "forest_tests/lp_3groups_test22.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_3groups_test23.in"),
          std::string(TESTS_DIR "forest_tests/lp_3groups_test23.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_3groups_test24.in"),
          std::string(TESTS_DIR "forest_tests/lp_3groups_test24.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_3groups_test25.in"),
          std::string(TESTS_DIR "forest_tests/lp_3groups_test25.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_3groups_test26.in"),
          std::string(TESTS_DIR "forest_tests/lp_3groups_test26.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_3groups_test27.in"),
          std::string(TESTS_DIR "forest_tests/lp_3groups_test27.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_3groups_test28.in"),
          std::string(TESTS_DIR "forest_tests/lp_3groups_test28.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_3groups_test29.in"),
          std::string(TESTS_DIR "forest_tests/lp_3groups_test29.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_3groups_test30.in"),
          std::string(TESTS_DIR "forest_tests/lp_3groups_test30.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_3groups_test31.in"),
          std::string(TESTS_DIR "forest_tests/lp_3groups_test31.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_3groups_test32.in"),
          std::string(TESTS_DIR "forest_tests/lp_3groups_test32.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_3groups_test33.in"),
          std::string(TESTS_DIR "forest_tests/lp_3groups_test33.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_3groups_test34.in"),
          std::string(TESTS_DIR "forest_tests/lp_3groups_test34.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_3groups_test35.in"),
          std::string(TESTS_DIR "forest_tests/lp_3groups_test35.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_3groups_test36.in"),
          std::string(TESTS_DIR "forest_tests/lp_3groups_test36.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_3groups_test37.in"),
          std::string(TESTS_DIR "forest_tests/lp_3groups_test37.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_3groups_test38.in"),
          std::string(TESTS_DIR "forest_tests/lp_3groups_test38.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_3groups_test39.in"),
          std::string(TESTS_DIR "forest_tests/lp_3groups_test39.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_3groups_test40.in"),
          std::string(TESTS_DIR "forest_tests/lp_3groups_test40.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_3groups_test41.in"),
          std::string(TESTS_DIR "forest_tests/lp_3groups_test41.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_3groups_test42.in"),
          std::string(TESTS_DIR "forest_tests/lp_3groups_test42.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_3groups_test43.in"),
          std::string(TESTS_DIR "forest_tests/lp_3groups_test43.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_3groups_test44.in"),
          std::string(TESTS_DIR "forest_tests/lp_3groups_test44.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_3groups_test45.in"),
          std::string(TESTS_DIR "forest_tests/lp_3groups_test45.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_3groups_test46.in"),
          std::string(TESTS_DIR "forest_tests/lp_3groups_test46.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_3groups_test47.in"),
          std::string(TESTS_DIR "forest_tests/lp_3groups_test47.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_3groups_test48.in"),
          std::string(TESTS_DIR "forest_tests/lp_3groups_test48.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_3groups_test49.in"),
          std::string(TESTS_DIR "forest_tests/lp_3groups_test49.out")),
      SteinerParam(std::string(TESTS_DIR "forest_tests/lp_3groups_test50.in"),
          std::string(TESTS_DIR "forest_tests/lp_3groups_test50.out"))));
