# NOTE: in order to exclusion rule work you have to use full path with leading './'
BLOSSOM5_SOURCES := $(shell find ./blossom5/ -name "*.cpp")
BLOSSOM5_DEPENDS := $(subst .cpp,.d, $(BLOSSOM5_SOURCES))
BLOSSOM5_OBJECTS := $(filter-out $(MAINOBJECTS),$(subst .cpp,.o, $(BLOSSOM5_SOURCES)))

blossom5/example: $(BLOSSOM5_OBJECTS)
experiments/tsp_christofides: $(BLOSSOM5_OBJECTS)
experiments/tsp/tsp_comparison: $(BLOSSOM5_OBJECTS)
$(GTEST): $(BLOSSOM5_OBJECTS)

# Hack to ignore warnings in blossom5 files.

CLEAN_DEPENDS := $(filter-out $(BLOSSOM5_DEPENDS), $(CLEAN_DEPENDS))

$(BLOSSOM5_DEPENDS) : %.d : %.cpp
	$(CXX) $(CXXFLAGS) -MT $(<:.cpp=.o) -MM $< > $@
	@echo -e "\t"$(CXX) -std=gnu++0x -w $(OPTIMIZATIONS) -c $(CFLAGS) $< -o $(<:.cpp=.o) >> $@
