# NOTE: in order to exclusion rule work you have to use full path with leading './'
BLOSSOM5_SOURCES := $(shell find ./blossom5/ -name "*.cpp")
BLOSSOM5_DEPENDS := $(subst .cpp,.d, $(BLOSSOM5_SOURCES))
BLOSSOM5_OBJECTS := $(filter-out $(MAINOBJECTS),$(subst .cpp,.o, $(BLOSSOM5_SOURCES)))

blossom5/example: $(BLOSSOM5_OBJECTS)
experiments/tsp_christofides: $(BLOSSOM5_OBJECTS)
$(GTEST): $(BLOSSOM5_OBJECTS)
