PAPER_TEX       :=	pdflatex -interaction=batchmode
PAPER_TEX_DRAFT :=	$(PAPER_TEX) -draft

PAPER_FILES	:=	$(wildcard paper/*.tex)
PAPER_MAIN	:=	paper/paal.pdf

paper: $(PAPER_MAIN)

$(PAPER_MAIN) : %.pdf : %.tex %.bib $(PAPER_FILES)
	cd $(<D); \
		$(PAPER_TEX_DRAFT) $(<F); \
		bibtex $(<F:.tex=.aux); \
		$(PAPER_TEX_DRAFT) $(<F); \
		$(PAPER_TEX) $(<F); \

clean-paper:
	-rm -f paper/*.{aux,log,err,bbl,toc,blg}
	-rm -f $(PAPER_MAIN)

clean: clean-paper

.PHONY: clean-paper paper
